name: Node.js Key JavaScript features

on: [push]

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Node.js Script
      run: node app.js